[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  functions = "netlify/functions"  # Ruta a tus funciones
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200